# Combine Predictions
Quickly combine the predictions of 2 models using a weighted average.

## Import

In [38]:
import pandas as pd
import numpy as np

#weight to use. (e.g.)
df1_weight = 10
df2_weight = 1

#df1 and df2 contain the model predictions to be combined
df1 = pd.read_csv('/Users/eloiserosen/Downloads/submission.csv')
df2 = pd.read_csv('/Users/eloiserosen/Downloads/RF.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')

## Check that column headings and row numbers match

In [39]:
# check column headings match
col1 = list(df1.columns.values)
col2 = list(df2.columns.values)
intersection = set(col1).intersection(col2)
intersection = list(intersection)

print len(col1)
print len(col2)
print len(intersection)

print intersection

40
40
40
['KIDNAPPING', 'WEAPON LAWS', 'SECONDARY CODES', 'WARRANTS', 'LOITERING', 'EMBEZZLEMENT', 'SUICIDE', 'DRIVING UNDER THE INFLUENCE', 'VEHICLE THEFT', 'ROBBERY', 'BURGLARY', 'STOLEN PROPERTY', 'PORNOGRAPHY/OBSCENE MAT', 'SUSPICIOUS OCC', 'ARSON', 'BRIBERY', 'FORGERY/COUNTERFEITING', 'BAD CHECKS', 'DRUNKENNESS', 'GAMBLING', 'OTHER OFFENSES', 'RECOVERED VEHICLE', 'FRAUD', 'FAMILY OFFENSES', 'DRUG/NARCOTIC', 'SEX OFFENSES NON FORCIBLE', 'LARCENY/THEFT', 'VANDALISM', 'MISSING PERSON', 'LIQUOR LAWS', 'TRESPASS', 'TREA', 'SEX OFFENSES FORCIBLE', 'EXTORTION', 'ASSAULT', 'RUNAWAY', 'NON-CRIMINAL', 'DISORDERLY CONDUCT', 'Id', 'PROSTITUTION']

In [41]:
# check row numbers match
print len(df1.index)
print len(df2.index)

884262
884262

## Combine

In [42]:
#new df
df3 = pd.DataFrame(data=None, columns=df1.columns,index=df1.index)
df3.head()

,Id,ARSON,ASSAULT,BAD CHECKS,BRIBERY,BURGLARY,DISORDERLY CONDUCT,DRIVING UNDER THE INFLUENCE,DRUG/NARCOTIC,DRUNKENNESS,...,SEX OFFENSES NON FORCIBLE,STOLEN PROPERTY,SUICIDE,SUSPICIOUS OCC,TREA,TRESPASS,VANDALISM,VEHICLE THEFT,WARRANTS,WEAPON LAWS
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#fill with weighted average
for word in col1:
    df3[word] = (df1[word]*df1_weight + df2[word]*df2_weight)/(df1_weight+df2_weight)

In [44]:
df3.head()

,Id,ARSON,ASSAULT,BAD CHECKS,BRIBERY,BURGLARY,DISORDERLY CONDUCT,DRIVING UNDER THE INFLUENCE,DRUG/NARCOTIC,DRUNKENNESS,...,SEX OFFENSES NON FORCIBLE,STOLEN PROPERTY,SUICIDE,SUSPICIOUS OCC,TREA,TRESPASS,VANDALISM,VEHICLE THEFT,WARRANTS,WEAPON LAWS
0,0,0.004282,0.155833,0.000049,0.000863,0.017408,0.001361,0.007383,0.027859,0.003360,...,0.000373,0.003521,0.000155,0.054605,0.000161,0.010129,0.053414,0.158732,0.019114,0.044805
1,1,0.005081,0.052046,0.000043,0.000427,0.000497,0.001252,0.009625,0.062054,0.005089,...,0.000056,0.005772,0.000281,0.030551,0.000121,0.000436,0.012128,0.020658,0.129944,0.049111
2,2,0.005056,0.139546,0.000160,0.000204,0.057441,0.001245,0.003326,0.024080,0.007223,...,0.000016,0.008778,0.000178,0.034483,0.000015,0.009651,0.055864,0.042907,0.050004,0.006333
3,3,0.002548,0.181044,0.000038,0.000738,0.029286,0.002897,0.003133,0.019247,0.010863,...,0.000228,0.004714,0.001083,0.047166,0.000030,0.005142,0.091542,0.134437,0.027403,0.016295
4,4,0.002548,0.181044,0.000038,0.000738,0.029286,0.002897,0.003133,0.019247,0.010863,...,0.000228,0.004714,0.001083,0.047166,0.000030,0.005142,0.091542,0.134437,0.027403,0.016295

# Output CSV

In [45]:
df3.to_csv('combined_output.csv', index=False)